name: Test pipeline

on:
  schedule:
     - cron: 30 18 * * *
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 22
      uses: actions/setup-java@v4
      with:
        java-version: '22'
        distribution: 'temurin'
        cache: maven
        
    - name: Running test automation framework
      run: mvn test -X -Dbrowser=chrome -DisLambdaTest=true -DisHeadless=false
       
    - name: Upload Test Logs
      if: always()
      uses: actions/upload-artifact@v4.6.0
      with:
        name: upload Test Log
        path: logs/

    - name: Upload Test Reports
      if: always()
      uses: actions/upload-artifact@v4.6.0
      with:
        name: Test Report
        path: report.html
    
    - name: Test execution status
      uses: echo "Test automation completed"
      
